#sdk: "~/GitHub/rhodes"
sdkversion: 5.0.0
name: testclient
version: 1.0
vendor: rhomobile
build: debug
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphoneos8.4
  provisionprofile:
  codesignidentity: iPhone Developer
  entitlements: ""
  BundleIdentifier: com.rhomobile.testclient
  BundleURLScheme: testclient
  production:
    ipa_itunesartwork_image: "./production/iTunesArtwork.png"  
wp8:
  productid: '9278e170-28d2-0133-c16a-6c4008b503f8'
android:
  manifest_template: 'AndroidManifest.erb'
  version: 2.3.3
  # Note: in order to simplify debugging only app messages and system channels with priority informative and higher, and any errors are enabled by default
  logcatFilter: APP:I StrictMode:I DEBUG:I *:E
  android_title: 0

wm:
  #sdk: "MC3000c50b (ARMV4I)"
  #sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"

extensions: ["rhoconnect-client"]

#paths:
#  extensions:
#  - /Users/home/GitHub/Motorola-Extensions/extensions
#  - /Users/home/GitHub/Motorola-Extensions/lib/commonAPI
#  - /Users/home/GitHub/rhoconnect-client/ext
app_type: rhoelements

encrypt_database: 0
